---
exclude: ^static/.*|assets/.*|\.min\.js$|\.min\.css$|\.css\.map$|\.min\.js$|\.js\.map$|\.svg$
default_stages: [pre-commit]
default_language_version:
    python: python3.14

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c59bba8fb259db0fec2bbb77ad8ba51ea7341b56  # frozen: v0.15.20
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
        - id: trailing-whitespace
          args: [--markdown-linebreak-ext=md]
        - id: end-of-file-fixer
        - id: check-yaml
        - id: mixed-line-ending
          args: [--fix=lf]
        - id: check-merge-conflict
  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a  # frozen: v2.4.2
    hooks:
        - id: codespell
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: a4d5d37e66ebcd6b3705204a1d6dbb56dea66338  # frozen: v0.49.0
    hooks:
        - id: markdownlint
          args: [--config, .markdownlint.yaml, --fix]
